[package]
name = "app_net"
version = "0.1.0"
edition.workspace = true


[dependencies]
tokio = { workspace = true }
dashmap = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }
