name: CI

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    name: Cargo test (workspace)
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Instala Rust (estable) de forma rápida y confiable
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Cache inteligente para workspaces (target/, ~/.cargo/, etc.)
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          # Ajusta si quieres granularidad por package/lockfile
          save-if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}

      # Opcional: verifica que compila todo (incluye bins, tests, examples, benches)
      - name: Build (all targets)
        run: cargo build --workspace --all-targets --locked

      # Corre todos los tests de todo el workspace y con todas las features
      - name: Test (all features)
        run: cargo test --workspace --all-features --all-targets --locked
